-- Integrate this SQL into the first table-creating Prisma migration *after* the
-- corresponding CREATE TABLE statements. Do not apply it as a pre-table migration.
-- Review identifiers against the SQL generated by the pinned Prisma version.

ALTER TABLE "listings"
  ADD COLUMN IF NOT EXISTS "geo_point" geography(Point, 4326)
  GENERATED ALWAYS AS (
    CASE
      WHEN "longitude" IS NULL OR "latitude" IS NULL THEN NULL
      ELSE ST_SetSRID(
        ST_MakePoint("longitude"::double precision, "latitude"::double precision),
        4326
      )::geography
    END
  ) STORED;

CREATE INDEX IF NOT EXISTS "listings_geo_point_gist"
  ON "listings" USING GIST ("geo_point");

CREATE INDEX IF NOT EXISTS "listings_title_trgm"
  ON "listings" USING GIN ("title" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS "listings_published_partial"
  ON "listings" ("type", "region_id", "published_at" DESC)
  WHERE "status" = 'PUBLISHED' AND "deleted_at" IS NULL;

ALTER TABLE "reviews" DROP CONSTRAINT IF EXISTS "reviews_rating_check";
ALTER TABLE "reviews"
  ADD CONSTRAINT "reviews_rating_check" CHECK ("rating" BETWEEN 1 AND 5);

ALTER TABLE "orders" DROP CONSTRAINT IF EXISTS "orders_subject_check";
ALTER TABLE "orders"
  ADD CONSTRAINT "orders_subject_check"
  CHECK ("user_id" IS NOT NULL OR "organization_id" IS NOT NULL);
